### ISSUE TITLE
[BUG]  django.db.utils.NotSupportedError: PostgreSQL 12 or later is required (found 11.18)

### ISSUE THREAD

**Issue by oh01** [Uninett/navappliance#8]
### Describe the bug

Hello, after upgrading from 5.12.0 to latest NAV 5.13.0 on prebuilt appliance with Debian 11, the webinterface is unavaliable and we got an error in Apache log that Django needs PostgreSQL 12. If i check with "psql -V" we are running version 13 (`psql (PostgreSQL) 13.20 (Debian 13.20-0+deb11u1)`) and with "pg_config --version" as well (`PostgreSQL 13.20 (Debian 13.20-0+deb11u1)`)

### Tracebacks from apache

```pytb
[Mon Mar 10 09:35:52.609821 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545] [Mon Mar 10 09:35:42 2025] [ERROR] [pid=667 django.request] Internal Server Error: /refresh_session/
[Mon Mar 10 09:35:52.609866 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545] Traceback (most recent call last):
[Mon Mar 10 09:35:52.609873 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py", line 187, in _get_session
[Mon Mar 10 09:35:52.609879 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     return self._session_cache
[Mon Mar 10 09:35:52.609885 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545] AttributeError: 'SessionStore' object has no attribute '_session_cache'
[Mon Mar 10 09:35:52.609894 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]
[Mon Mar 10 09:35:52.609902 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545] During handling of the above exception, another exception occurred:
[Mon Mar 10 09:35:52.609916 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545] Traceback (most recent call last):
[Mon Mar 10 09:35:52.609922 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
[Mon Mar 10 09:35:52.609928 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     response = get_response(request)
[Mon Mar 10 09:35:52.609933 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/utils/deprecation.py", line 133, in __call__
[Mon Mar 10 09:35:52.609938 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     response = self.process_request(request)
[Mon Mar 10 09:35:52.609944 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/nav/web/auth/middleware.py", line 43, in process_request
[Mon Mar 10 09:35:52.609949 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     dict(request.session),
[Mon Mar 10 09:35:52.609954 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py", line 123, in keys
[Mon Mar 10 09:35:52.609960 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     return self._session.keys()
[Mon Mar 10 09:35:52.609965 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py", line 192, in _get_session
[Mon Mar 10 09:35:52.609971 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     self._session_cache = self.load()
[Mon Mar 10 09:35:52.610089 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 42, in load
[Mon Mar 10 09:35:52.610096 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     s = self._get_session_from_db()
[Mon Mar 10 09:35:52.610101 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
[Mon Mar 10 09:35:52.610107 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     return self.model.objects.get(
[Mon Mar 10 09:35:52.610112 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
[Mon Mar 10 09:35:52.610118 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[Mon Mar 10 09:35:52.610124 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/db/models/query.py", line 633, in get
[Mon Mar 10 09:35:52.610129 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     num = len(clone)
[Mon Mar 10 09:35:52.610135 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/db/models/query.py", line 380, in __len__
[Mon Mar 10 09:35:52.610140 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     self._fetch_all()
[Mon Mar 10 09:35:52.610146 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/db/models/query.py", line 1881, in _fetch_all
[Mon Mar 10 09:35:52.610151 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     self._result_cache = list(self._iterable_class(self))
[Mon Mar 10 09:35:52.610156 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/db/models/query.py", line 91, in __iter__
[Mon Mar 10 09:35:52.610239 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     results = compiler.execute_sql(
[Mon Mar 10 09:35:52.610245 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
[Mon Mar 10 09:35:52.610251 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     cursor = self.connection.cursor()
[Mon Mar 10 09:35:52.610256 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
[Mon Mar 10 09:35:52.610262 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     return func(*args, **kwargs)
[Mon Mar 10 09:35:52.610267 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/db/backends/base/base.py", line 330, in cursor
[Mon Mar 10 09:35:52.610273 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     return self._cursor()
[Mon Mar 10 09:35:52.610279 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/db/backends/base/base.py", line 306, in _cursor
[Mon Mar 10 09:35:52.610285 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     self.ensure_connection()
[Mon Mar 10 09:35:52.610290 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
[Mon Mar 10 09:35:52.610295 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     return func(*args, **kwargs)
[Mon Mar 10 09:35:52.610301 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
[Mon Mar 10 09:35:52.610317 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     self.connect()
[Mon Mar 10 09:35:52.610322 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
[Mon Mar 10 09:35:52.610328 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     return func(*args, **kwargs)
[Mon Mar 10 09:35:52.610333 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/db/backends/base/base.py", line 272, in connect
[Mon Mar 10 09:35:52.610339 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     self.init_connection_state()
[Mon Mar 10 09:35:52.610345 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 309, in init_connection_state
[Mon Mar 10 09:35:52.610350 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     super().init_connection_state()
[Mon Mar 10 09:35:52.610356 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/db/backends/base/base.py", line 239, in init_connection_state
[Mon Mar 10 09:35:52.610362 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     self.check_database_version_supported()
[Mon Mar 10 09:35:52.610367 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]   File "/opt/venvs/nav/lib/python3.9/site-packages/django/db/backends/base/base.py", line 214, in check_database_version_supported
[Mon Mar 10 09:35:52.610373 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545]     raise NotSupportedError(
[Mon Mar 10 09:35:52.610379 2025] [wsgi:error] [pid 667:tid 743] [remote X.X.X.X:64545] django.db.utils.NotSupportedError: PostgreSQL 12 or later is required (found 11.18).
```

### Environment:

 - OS on the NAV server: Debian 11
 - NAV version installed: 5.13.0
 - Method of installation: Originally Virtual Appliance, upgraded to latest with deb package from NAV Debian repository

**Comment by oh01** [comment]
Can I help with this to troubleshoot it more to find out why it's saying there is only PSQL 11 eventough 13 is installed? Right now we have hold the package to stay on NAV 5.12.0 (otherwise nav won't start after upgrade at all).

Thank you.

**Comment by lunkwill42** [comment]
Are we talking about this appliance: https://github.com/uninett/navappliance ?  In that case, this report probably belongs in that repo.

Doing `psql -v` will not tell you which version of the PostgreSQL server is running, it will tell you which version of PostgreSQL the `psql` client program was built from.

Did you upgrade the appliance from an earlier version of Debian?  If so, you should really check which version of PostgreSQL is serving port *5432* using the `pg_lsclusters` command.  Upgrading Debian will not automatically upgrade your existing database clusters, it will just install a new version of PostgreSQL in parallel to the one you were already running.

**Comment by oh01** [comment]
Hello lunkwill42,
thank your for your message, I meant that appliance, which was originally upgraded from debian 9 to 11 some time ago.

There were indeed 2 postgres clusters running which I didn't realize before. After droping the new one and running `pg_upgradecluster`, I've successfully upgraded the old 11 version to psql 13 and now NAV is working correctly after upgrading it to 5.13.

Thanks again.
